build_from:
  aarch64: "codeberg.org/forgejo/forgejo:12.0.1"
  amd64: "codeberg.org/forgejo/forgejo:12.0.1"
  armhf: "codeberg.org/forgejo/forgejo:12.0.1"
  armv7: "codeberg.org/forgejo/forgejo:12.0.1"
  i386: "codeberg.org/forgejo/forgejo:12.0.1"
